<?php
/**
 * Model class '{CLASS_NAME}' for Nitro
 * --
 * Empty class to add user-defined custom methods.
 * Nitro will never overwrite this class.
 * 
 * Generated by Nitro on {GEN_DATETIME}
 */

class {CLASS_NAME} extends Base{CLASS_NAME}
{

}